url="https://www.jrecommerce.com/demo.php"
emaillocator="xpath=//input[@id='input-email']"
passwordlocator="xpath=//input[@id='input-password']"
loginbtn="xpath=//input[@value='Login']"
logoutelement="xpath=//span[@id='cartme']"
customerlogin="xpath=//a[normalize-space()='Customer Login']"
logoutlogo="//span[@id='cartme']"
logoutbtn="//a[contains(text(),'Logout')]"
vendorlogin="//a[normalize-space()='Vendor Login']"
vendorlogout="//span[normalize-space()='Logout']"
vendorlogouttxt="Vendor Logout"